### ISSUE TITLE
TUXML version: Unable to find the missing package(s)

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/tuxml#8]
python3 kernel_generator.py --tiny --linux4_version 8.1 --dev 1
```
00:00:13 [2019-03-29 09:20:50 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:18 [2019-03-29 09:20:55 CET] [__compile] Compilation in progress
00:00:21 [2019-03-29 09:20:58 CET] [__compile] Compilation failed, exit status : 2.
00:00:21 [2019-03-29 09:20:58 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:21 [2019-03-29 09:20:58 CET] [__log_analyser] Unable to find the missing package(s).
00:00:21 [2019-03-29 09:20:58 CET] [__do_a_compilation] Unable to compile in 00:00:03 (installation_time = 00:00:00)
00:00:21 [2019-03-29 09:20:58 CET] [insert_result_into_database] Sending result to database.
00:00:21 [2019-03-29 09:20:58 CET] [insert_result_into_database] Successfully send result with cid : 76
```

python3 kernel_generator.py --tiny --linux4_version 8.1 --dev 1
```
00:00:07 [2019-03-29 09:21:44 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:10 [2019-03-29 09:21:47 CET] [__compile] Compilation in progress
00:00:12 [2019-03-29 09:21:49 CET] [__compile] Compilation failed, exit status : 2.
00:00:12 [2019-03-29 09:21:49 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:12 [2019-03-29 09:21:49 CET] [__log_analyser] Unable to find the missing package(s).
00:00:12 [2019-03-29 09:21:49 CET] [__do_a_compilation] Unable to compile in 00:00:02 (installation_time = 00:00:00)
00:00:12 [2019-03-29 09:21:49 CET] [insert_result_into_database] Sending result to database.
00:00:12 [2019-03-29 09:21:49 CET] [insert_result_into_database] Successfully send result with cid : 77
```

same with 7.1
```
00:00:08 [2019-03-29 09:25:26 CET] [__linux_config_generator] Tiny config with preset values here : /TuxML/compilation/x64.config .
00:00:11 [2019-03-29 09:25:29 CET] [__compile] Compilation in progress
00:00:13 [2019-03-29 09:25:31 CET] [__compile] Compilation failed, exit status : 2.
00:00:13 [2019-03-29 09:25:31 CET] [__log_analyser] Analysing /TuxML/logs/stderr.log
00:00:13 [2019-03-29 09:25:31 CET] [__log_analyser] Unable to find the missing package(s).
00:00:13 [2019-03-29 09:25:31 CET] [__do_a_compilation] Unable to compile in 00:00:02 (installation_time = 00:00:00)
00:00:13 [2019-03-29 09:25:31 CET] [insert_result_into_database] Sending result to database.
00:00:13 [2019-03-29 09:25:31 CET] [insert_result_into_database] Successfully send result with cid : 78
```

It works with version 9.1 !!

side note: it seems versioning support cannot be activated without having the "core" Docker images before (ie I clean my Docker images, and then directly use linux4_version: it fails; when I clean my Docker images, launch --tiny on the default version, and then linux4_version it works!)
